[project]
site_name = "Django GCP"
site_url = "https://django-gcp.readthedocs.io/"
site_description = "Utilities to run Django on Google Cloud Platform."
repo_url = "https://github.com/octue/django-gcp"
docs_dir = "docs"
site_dir = "site"
nav = [
  { "Home" = "index.md" },
  { "Getting started" = "getting-started.md" },
  { "Authentication" = [
    { "Overview" = "authentication/index.md" },
    { "Authenticating the server" = "authentication/server.md" },
    { "Authenticating endpoints" = "authentication/endpoints.md" },
    { "Adding authenticated endpoints" = "authentication/adding-authenticated-endpoints.md" },
  ] },
  { "Services" = [
    { "Overview" = "services/index.md" },
    { "Storage" = "services/storage.md" },
    { "Events" = "services/events.md" },
    { "Tasks" = [
      { "About" = "services/tasks/index.md" },
      { "Usage" = "services/tasks/usage.md" },
      { "Settings" = "services/tasks/settings.md" },
      { "Workers" = "services/tasks/workers.md" },
    ] },
    { "Workflows" = [
      { "About" = "services/workflows/index.md" },
      { "Usage" = "services/workflows/usage.md" },
      { "Tips" = "services/workflows/tips.md" },
    ] },
    { "Logs" = "services/logs.md" },
    { "Cloud Run" = "services/cloud-run.md" },
  ] },
  { "Settings" = [
    { "Django settings" = "settings/django-settings.md" },
    { "Environment variables" = "settings/environment-variables.md" },
  ] },
  { "Version history" = "version-history.md" },
  { "License" = "license.md" },
  { "Conventions" = [
    { "Documentation" = "conventions/documentation.md" },
    { "Branching" = "conventions/git-branching.md" },
    { "Commits and versioning" = "conventions/git-commits-and-versioning.md" },
    { "Pull requests" = "conventions/git-pull-requests.md" },
  ] },
]
