# Generated by Django 4.1.7 on 2023-04-12 07:02

import django_gcp.storage.fields
from django.db import migrations, models

import tests.server.example.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleBlankBlobFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "blob",
                    django_gcp.storage.fields.BlobField(
                        accept_mimetype="*/*",
                        blank=True,
                        default=dict,
                        get_destination_path=tests.server.example.models.get_destination_path,
                        help_text="GCP cloud storage object",
                        ingress_to="_tmp/",
                        null=True,
                        store_key="media",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExampleBlobFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "blob",
                    models.FileField(blank=True, null=True, upload_to="blob_uploads"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExampleStorageModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "normal",
                    models.FileField(blank=True, null=True, upload_to="normal_uploads"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExampleUneditableBlobFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "blob",
                    django_gcp.storage.fields.BlobField(
                        accept_mimetype="*/*",
                        default=dict,
                        editable=False,
                        get_destination_path=tests.server.example.models.get_destination_path,
                        help_text="GCP cloud storage object",
                        ingress_to="_tmp/",
                        store_key="media",
                    ),
                ),
            ],
        ),
    ]
