# Generated by Django 4.1.7 on 2023-06-12 14:53

from django.db import migrations, models

import django_gcp.storage.fields
import tests.server.example.models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0004_rename_blob_temp_exampleblobfieldmodel_blob"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleCallbackBlobFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "blob",
                    django_gcp.storage.fields.BlobField(
                        accept_mimetype="*/*",
                        blank=True,
                        default=None,
                        get_destination_path=tests.server.example.models.get_destination_path,
                        help_text="GCP cloud storage object",
                        ingress_to="_tmp/",
                        null=True,
                        on_change=tests.server.example.models.my_on_change_callback,
                        overwrite_mode="never",
                        store_key="media",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="exampleblankblobfieldmodel",
            name="blob",
            field=django_gcp.storage.fields.BlobField(
                accept_mimetype="*/*",
                blank=True,
                default=None,
                get_destination_path=tests.server.example.models.get_destination_path,
                help_text="GCP cloud storage object",
                ingress_to="_tmp/",
                null=True,
                on_change=None,
                overwrite_mode="never",
                store_key="media",
            ),
        ),
        migrations.AlterField(
            model_name="exampleblobfieldmodel",
            name="blob",
            field=django_gcp.storage.fields.BlobField(
                accept_mimetype="*/*",
                default=None,
                get_destination_path=tests.server.example.models.get_destination_path,
                help_text="GCP cloud storage object",
                ingress_to="_tmp/",
                on_change=None,
                overwrite_mode="never",
                store_key="media",
            ),
        ),
        migrations.AlterField(
            model_name="exampleuneditableblobfieldmodel",
            name="blob",
            field=django_gcp.storage.fields.BlobField(
                accept_mimetype="*/*",
                default=None,
                editable=False,
                get_destination_path=tests.server.example.models.get_destination_path,
                help_text="GCP cloud storage object",
                ingress_to="_tmp/",
                on_change=None,
                overwrite_mode="never",
                store_key="media",
            ),
        ),
    ]
