# Generated by Django 4.1.7 on 2023-11-17 15:19

from django.db import migrations, models

import django_gcp.storage.fields
import tests.server.example.models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0005_examplecallbackblobfieldmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleMultipleBlobFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "blob1",
                    django_gcp.storage.fields.BlobField(
                        accept_mimetype="*/*",
                        default=None,
                        get_destination_path=tests.server.example.models.get_destination_path,
                        help_text="GCP cloud storage object",
                        ingress_to="_tmp/",
                        on_change=None,
                        overwrite_mode="never",
                        store_key="media",
                    ),
                ),
                (
                    "blob2",
                    django_gcp.storage.fields.BlobField(
                        accept_mimetype="*/*",
                        default=None,
                        get_destination_path=tests.server.example.models.get_destination_path,
                        help_text="GCP cloud storage object",
                        ingress_to="_tmp/",
                        on_change=None,
                        overwrite_mode="never",
                        store_key="media",
                    ),
                ),
                (
                    "blob3",
                    django_gcp.storage.fields.BlobField(
                        accept_mimetype="*/*",
                        default=None,
                        get_destination_path=tests.server.example.models.get_destination_path,
                        help_text="GCP cloud storage object",
                        ingress_to="_tmp/",
                        on_change=None,
                        overwrite_mode="never",
                        store_key="media",
                    ),
                ),
            ],
        ),
    ]
