# Generated by Django 4.2.19 on 2025-03-20 13:00

from django.db import migrations, models
import django_gcp.storage.fields
import tests.server.example.models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0007_exampleneveroverwriteblobfieldmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleUpdateAttributesBlobFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "blob",
                    django_gcp.storage.fields.BlobField(
                        accept_mimetype="*/*",
                        blank=True,
                        default=None,
                        get_destination_path=tests.server.example.models.get_destination_path,
                        help_text="On save, metadata should be updated on the blob.",
                        ingress_to="_tmp/",
                        null=True,
                        on_change=None,
                        overwrite_mode="never",
                        store_key="media",
                        update_attributes=tests.server.example.models.update_attributes,
                    ),
                ),
            ],
        ),
    ]
